# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monaifl_pb2 as monaifl__pb2


class MonaiFLServiceStub(object):
    """service method
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParamTransfer = channel.unary_unary(
                '/protobufs.MonaiFLService/ParamTransfer',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )


class MonaiFLServiceServicer(object):
    """service method
    """

    def ParamTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonaiFLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParamTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ParamTransfer,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobufs.MonaiFLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonaiFLService(object):
    """service method
    """

    @staticmethod
    def ParamTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/ParamTransfer',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
